"""empty message

Revision ID: 339c873234e8
Revises: a267597f1980
Create Date: 2023-11-08 15:28:52.245207

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "339c873234e8"
down_revision = "a267597f1980"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("email", sa.String(), nullable=False))
        batch_op.create_unique_constraint("email_not_none", ["email"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint("email_not_none", type_="unique")
        batch_op.drop_column("email")

    # ### end Alembic commands ###
